### ISSUE TITLE
Dropped connection disables plugin, doesnt auto reconnect

### ISSUE THREAD

**Issue by baronvertigovongrahamthefirstofsealand** [jgeboski/purple-facebook#89] opened 2015-08-06 19:46 UTC
If your internet connection drops for whatever reason, the plugin disables itself.

Would much prefer if it didnt, and instead tried to auto reconnection.

**Comment by jgeboski** [comment] 2015-08-06 19:56
Plugin version?

**Comment by PorcelainMouse** [comment] 2015-08-10 08:58
How do you know what version you have?  Best I can tell, I'm on commit 9faa209. I just rebuilt a couple of days ago after using update.sh to update my git working tree.  Is that right?

Thanks to jgeboski for reporting this.  I was getting this a lot and wondering why no one else had reported it.

**Comment by jgeboski** [comment] 2015-08-10 16:56
Go to `Help => Plugin Information`.

**Comment by PorcelainMouse** [comment] 2015-08-10 18:39
Help > Plugin Info shows a34b993324e4 .
(But, the plugin doesn't show up in the Tools > Plugins list.  Is that right?)
I'm update.sh-ing again....

**Comment by jgeboski** [comment] 2015-08-10 18:48
Yeah, `a34b993324e4` is over a month old at this point.  Tons of changes since then, including ones related to error handling.  You need to grab the latest source from here, first.  Then, you can use `./update.sh`.  The `./update.sh` script does not do what you think it does.  It simply builds up the source tree from a hard-coded mercurial hash.

**Comment by PorcelainMouse** [comment] 2015-08-11 05:11
Okay, now I have 9e3520d6ec49 running.  Sorry, didn't mean to hijack this bug report.  Thanks for your help.  I'll report back here if it keeps happening.

**Comment by jgeboski** [comment] 2015-08-11 05:45
Also, note, I does take between 8 seconds and a minute for the account to reconnect on its own.

**Comment by PorcelainMouse** [comment] 2015-08-11 06:45
Okay, good to know.

But, it should *not* say "account disabled," right?  The message we get is that it is not (or is no longer) attempting to reconnect.

**Comment by jgeboski** [comment] 2015-08-11 18:22
Correct.  What is the exact error it is giving you?

**Comment by PorcelainMouse** [comment] 2015-08-11 21:56
I'll let you know if it happens again, but it hasn't since I updated.  I know there was one network blip already, and it is still connected; so, perhaps this version doesn't have the problem.  It's been happening once a day since I started using the FB account plugin about a month ago.  I'll give it a week and let you know.

(It was something like, "... disconnected ... the account <FB Account> has been disabled.  Change the account settings and re-enable the account."  There are two buttons, "cancel" and "re-enable account.")

**Comment by PorcelainMouse** [comment] 2015-08-13 06:23
Okay, it finally recurred.  It survived two other blips, AFAIK, but this last recurrence correlates with the most recent blip.  I would be more concerned with these blips if they were affecting my other accounts, but it's only the FB connection that is breaking.  Here is the error:

<username> (Facebook) disconnected.
Failed to read fixed header
Finch will not attempt to reconnect the account until you correct the error and re-enable the account.
[OK] [Modify Account] [Re-enable Account]

(I'm *not* sure this is exactly the same as past errors, but very nearly.)

**Comment by dequis** [comment] 2015-08-13 19:46
@PorcelainMouse does this happen with pidgin too, or only with finch?

As far as I can see finch provides no decent way to output verbose debug logs (the debug window doesn't count as decent) or to even check the version of the plugin you're using.

**Comment by PorcelainMouse** [comment] 2015-08-13 22:30
I'm not sure.  But, I'm happy to test; I'll use it for the next week and see if it recurs.  I take it you are using Pidgin and this doesn't happen for you, right?  I think we should ask @baronvertigovongrahamthefirstofsealand though, too; that could settle the issue, quicker.

**Comment by PorcelainMouse** [comment] 2015-08-14 18:53
Okay, it recurred with Pidigin, too.  I'm sorry I didn't check every word of the error message, but I'm pretty sure it was the same.

Here's what I assume is relevant output from the debug log:
(10:32:44) connection: Connection error on 0x2b70170 (reason: 16 description: Failed to read fixe
d header)
(10:32:44) account: Disconnecting account <FB username>
(10:32:44) connection: Disconnecting connection 0x2b70170
(10:32:44) connection: Destroying connection 0x2b70170

According to the timestamps, this happened a few minutes after I noticed a network blip.

**Comment by jgeboski** [comment] 2015-08-14 18:55
And this doesn't reconnect at any point within a *minute* after disconnection?

**Comment by PorcelainMouse** [comment] 2015-08-14 18:57
No, I noticed the error msg at 11:47, but it disconnected more than an hour before.

**Comment by PorcelainMouse** [comment] 2015-08-14 18:59
Also, I do have the exact error msg:
**`<FB username>` disabled**
Failed to read fixed header
[Modify Account][Re-enable]

**Comment by dequis** [comment] 2015-08-15 00:51
Tried to reproduce this issue, and as expected, it says `reason: 0` instead of `reason: 16`

`(21:35:21) connection: Connection error on 0x1f35f80 (reason: 0 description: Failed to read fixed header)`

Same thing in 9e3520d6ec49 (the one before last) and 3d30d24fdbef (latest)

I honestly have no idea. Let's do a sanity check. Run this from the root of the git repo:

    sed -i 's/fixed header"/& ". Version: " PACKAGE_VERSION/' pidgin/libpurple/protocols/facebook/mqtt.c

And then `make`, `sudo make install` as usual. (If you do `./update.sh` after the sed command it will drop this change. Don't do that now.)

The error message should change to `Failed to read fixed header 9e3520d6ec49` or `Failed to read fixed header 3d30d24fdbef`.

If it doesn't mention a version that would mean you're still running the old one, which would be a good thing since otherwise this wouldn't make any sense. If it does mention a version and still says `reason: 16` then wat.

**Comment by PorcelainMouse** [comment] 2015-08-18 01:22
Hmm, okay, well, here's what I got.  It happened again and spit out: Version 9e3520d6ec49

No reason was given.
This is interesting because I did what you said, but didn't end up with the latest version, I got the previous version.  It also says my WD is clean even though that file you had me modify is obviously changed.  I've been using git for a long time, but I'm not expert and I'm confused by this.

**Comment by PorcelainMouse** [comment] 2015-08-24 23:01
Here is some more information.  I've been running pidgin for the past 7 days and didn't have this problem, even though I have experienced many ISP blips.  I switched back to finch and the problem recurred in a few hours even without with any ISP blips.  So, there may be a correlation with finch, but it *did* happen with pidgin and 9e3520d6ec49, once.  So, I don't know what to make of it.

(Just to be clear, when I say 'blip', I'm referring to uncharacteristically large ping times (2000+ms) from a router just a hop or two upstream.)

I'll keep testing and report here.  Should I run update.sh again to get the latest version?

Also, if anyone else is having this problem, please say so.  I don't think @baronvertigovongrahamthefirstofsealand  has added anything since opening this issue.

**Comment by jgeboski** [comment] 2015-08-24 23:06
Thanks for the update!  Sounds like it might be a Finch bug.

> I'll keep testing and report here. Should I run update.sh again to get the latest version?

You need to pull from git, and then `./update.sh`.  The `./update.sh` script only builds a local source tree.  I should probably rename the script, as it does seem to be misleading and cause confusion.

> Also, if anyone else is having this problem, please say so. I don't think @baronvertigovongrahamthefirstofsealand has added anything since opening this issue.

This is your issue at this point.  I would have closed this issue long ago had it not been for your contributions.

**Comment by fangfufu** [comment] 2015-08-27 04:21
I am experiencing similar issue. I do recall it was once fixed before. I am not sure how to diagnose it.

**Comment by dequis** [comment] 2015-08-27 04:23
@fangfufu same error? also with finch?

**Comment by fangfufu** [comment] 2015-08-27 05:14
@dequis, when my connection gets interrupted, purple-facebook doesn't automatically reconnect. It seems to be stuck in the process of reconnecting. No, I am not using finch. I am using pidgin.

**Comment by PorcelainMouse** [comment] 2015-08-27 21:49
@fangfufu , it's important to match the exact error, i.e. "account disabled...failed to read fixed header".  In this bug, I find my client *not* trying to reconnect.  It explicitly says it has stopped trying to reconnect and has "disabled" the FB account.  All other accounts are still active or have successfully reconnected by the time I notice.  Are you sure this is the same for you?

Meanwhile, I've been testing with Finch all week and it has now survived three major blips where my ping test completely timed out.  That is the maximum delay I can measure with this simple test and I expect to see this FB problem when that happens, but it didn't.  So, the correlation with simple network delay is there, but only at medium strength.  Also, it seems to be better with the current version I rebuilt over the weekend (strings says 39b8f418563c, now).

**Comment by fangfufu** [comment] 2015-08-28 08:51
My status icon shows a spinning circle. It looks like it is trying to
reconnect, but stuck in some kind of loop. There is no error message
whatsoever.

Should I open a new ticket? I am not sure if we are on the same page.

**Comment by kaberett** [comment] 2015-09-05 15:15
I'm reproducing using Pidgin version 2.10.11, plugin version 20150827~b1c35a6~6a0a79182ebc~22 under Debian Jessie (64-bit). I'm also finding that after my connection drops, my Facebook account isn't reconnecting (but other accounts including gchat are). Status drop-down shows the spinning circle and text "Connecting..." forever. Disabling and then reenabling my Facebook account as a workaround does mean I end up connecting but is faff; please let me know if further information might be helpful (and thank you *so much* for writing & maintaining this plug-in; my mother is very grateful to you!).

**Comment by PorcelainMouse** [comment] 2015-09-07 00:02
Previously, I would have said, 'yes, open a new ticket' because that behavior is not what this bug is about.  But, now, I'm not so sure.  I was MIA for a week and I found that finch didn't disable my FB account the whole time!  So, either the bug I reported is gone or FB changed something on their end that causes this plug-in to behave differently, avoiding the code path that causes permanent account disabling, but still unable to reconnect efficiently.

@jgeboski : Let us know if you want to keep tracking this here or open a new ticket.  From what I can tell, the original symptom is gone, so, I can understand closing it.

It is interesting that you two other reporters see long reconnection times.  Does it eventually reconnect or are you sure it will never reconnect by itself?  How long did you wait?  I mean, I didn't check finch for like 4 days, so, if it took 24 hours to reconnect, I wouldn't know.

(However, finch did spew a bunch of programmer credits on the screen.  Obviously a different symptom, but I'm sure it's also related to connectivity issues.  Did any of you happen to see that in pidgin, too?  I couldn't tell if they were finch programmers, lib-purple programmers, or plug-in programmers.  I'll check next time.)

**Comment by dequis** [comment] 2015-09-07 01:23
>finch did spew a bunch of programmer credits on the screen

wat

**Comment by marsjaninzmarsa** [comment] 2015-09-07 01:49
Are you using "Do not disturb" status? I have similar issue with DND - sometimes when I'm disconnected, Pidgin just spinning and spinning "Connecting" spinner, and simple workaround for me is changing status to "Online" and then back to DND.

**Comment by kaberett** [comment] 2015-09-07 13:38
I'm not normally waiting more than 12 hours, but certainly reconnection isn't succeeding up to that point (after connectivity outages of as little as 30 seconds in some cases) - it's not behaving like I'd expect back-off attempts to.

I'm not using DND status; I just experimented and changing status didn't prompt a reconnect.

**Comment by PorcelainMouse** [comment] 2015-09-08 03:47
@marsjaninzmarsa : No, I don't use DND status, I don't think.  Eventually, finch went into "away" status automatically, but I just left it that way all week.  So, we can eliminate changing status as a factor, too.

@dequis : Confused?  It was just a list of names, exactly like it sounds.  I assume they were contributing programmers, like credits at the end of a video game.  That's what it looked like, anyway.  They ran off the screen (remember, it's finch) so I couldn't see the title of the list.  It happened twice and if it happens again, I will copy the whole thing.

**Comment by curchunflo** [comment] 2015-09-11 19:20
I am having the "failed to read fixed header" error since the last 2 versions. Maybe james could include an auto-reconnect function so we have not to spent all the time clicking on reconnect

**Comment by kaberett** [comment] 2015-09-11 22:25
Additional datapoint: the plugin/Pidgin can't reconnect to Facebook if the connection dropping is due to dodgy signal or my machine _suspending_, but if my machine _hibernates_ then when powering back up out of hibernation, the plugin/Pidgin seems to reconnect without any problems.

**Comment by dequis** [comment] 2015-09-12 00:47
To everyone with this issue, please open the debug window and look for an error like this one when it disconnects:

```
(21:35:21) connection: Connection error on 0x1f35f80 (reason: 0 description: Failed to read fixed header)
```

And confirm whether it says `reason: 0` or `reason: 16`

**Comment by kaberett** [comment] 2015-09-13 14:07
reason: 0 for me.

**Comment by dequis** [comment] 2015-09-14 01:36
Reason 0 means `PURPLE_CONNECTION_ERROR_NETWORK_ERROR`, which will attempt to reconnect every time. That is not the same problem PorcelainMouse had, but this ticket is a mess already so whatever.

Maybe try disabling all other plugins?

**Comment by PorcelainMouse** [comment] 2015-09-27 17:46
Well, I don't think I've hat this problem since my last post 20 days ago.  So, something is much better, at least for me.  The network "blips" with which this event seem to correlate have been reduced, but are not totally gone, so that isn't the full story.

What about other people?  Are others still experiencing this regularly?

**Comment by dequis** [comment] 2015-09-27 17:54
There's other two issues, #138 and #143. I think networkmanager might be relevant. Do you use networkmanager?

**Comment by PorcelainMouse** [comment] 2015-09-27 18:03
Yes, I use NM.  I have a TODO item to switch to systemd, but haven't had the time; that's only been an option since F23 (May-ish?).  If it's NM, it would have to be a new NM bug, wouldn't it, or else more people would have seen it before now?  I don't know, I just started using the plugin recently.

In any case, my system is hard wire, not WiFi.  So, I don't suspect NM.  (Although, I've hated NM for more than a decade, so I wouldn't dismiss that idea off hand, either!)

**Comment by fangfufu** [comment] 2015-09-27 18:08
Yes, I use networkmanager.

**Comment by baronvertigovongrahamthefirstofsealand** [comment] 2015-10-16 21:54
Hello, OP here. Can confirm this happen on Pidgin. My version of this plugin is: 4098e875ebcb.

Ill update, and then report back if its been fixed.

**Comment by baronvertigovongrahamthefirstofsealand** [comment] 2015-11-04 03:06
Have been using version 6a0a79182ebc since last post, and this still occurs.

**Closed** 2015-11-04 03:10 UTC
Labels: unconfirmed
