### ISSUE TITLE
Own messages are marked unread when using other Facebook apps

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#161] opened 2015-10-31 17:38 UTC
I don't know if this is in the control of purple-facebook, but if I use the Messenger app and I send a message to my contact person, my own message appears in Pidgin unread.

I know that I sent that message, so Pidgin doesn't need to remind me.

**Comment by jgeboski** [comment] 2015-10-31 17:41
Duplicate of #131?

**Comment by Smile4ever** [comment] 2015-10-31 17:44
No. Because the conversation window is already open. I would like a "auto mark as read" when the sender == myself.

**Comment by jgeboski** [comment] 2015-12-28 21:41
Given the current limitations of the libpurple interfaces, this is not possible without digging into Pidgin or Finch. I have zero interest in doing anything which requires resources outside of libpurple. It really hinders the compatibility with other third-party clients.

The real issue is that there is no real self-message capability in libpurple, and this plugin has had to hack the functionality in. Maybe at some point in the future, the development version of libpurple will support such an interface.

**Closed by jgeboski** 2015-12-28 21:41 UTC
Labels: enhancement

**Comment by jgeboski** [comment] 2015-12-28 22:58
As of [609d20c](https://bitbucket.org/pidgin/main/commits/609d20c561629a67fc6094c87fa14fe8af998869), self messages can now be disabled. This patch will appear in the next release.

**Comment by Smile4ever** [comment] 2015-12-29 00:27
What do you mean? Are they still displayed in the conversation window when they are disabled? Will the default resolve this bug?

**Comment by jgeboski** [comment] 2015-12-29 00:59
> Are they still displayed in the conversation window when they are disabled?

Nope. The functionality is disable completely.

> Will the default resolve this bug?

Nope. By default, self messages are enabled. You will need to uncheck the box in the account settings.
