### ISSUE TITLE
Own messages in group chat are not shown when chatting using Messenger app

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#167] opened 2015-11-09 19:12 UTC
My own messages aren't inserted in the group chat (in Pidgin) that I have open when I use the Messenger app to reply in the group.

**Comment by jgeboski** [comment] 2015-12-28 19:47
I just retested this with the latest release, and it appears to function as expected. This must have been fixed by something else, as I do not remember this working as intended previously. Can you confirm this issue has been resolved?

**Comment by Smile4ever** [comment] 2015-12-28 20:15
I confirm this.

**Closed** 2015-12-28 20:15 UTC
Labels: bug
