### ISSUE TITLE
Does not reconnect after suspend&resume

### ISSUE THREAD

**Issue by Pastafarianist** [jgeboski/purple-facebook#138] opened 2015-09-16 09:13 UTC
When I resume from suspend, the plugin doesn't reconnect. The icon in the plugin list remains grey forever, and Pidgin's tray icon indicates a broken connection. Deactivating and activating the plugin solves the issue.

    $ uname -sr
    Linux 4.0.5-gentoo

    Pidgin 2.10.11 (libpurple 2.10.11)

    Facebook
    	Author: (null)
    	Version: 6a0a79182ebc
    	Website: https://github.com/jgeboski/purple-facebook
    	ID String: prpl-facebook
    	Loadable: Yes
    	Loaded: Yes

**Comment by samuelnilsson** [comment] 2015-09-16 14:46
I have the same problem. It seems to occur when the network reconnects to the same or a separate network, for example when returning from suspend. It works when restarting the plugin. I'm running Linux 4.1.6-1-ARCH and pidgin 2.10.11-2.

**Comment by Adirelle** [comment] 2015-11-01 09:09
I have the same issue, on both Windows (Pidgin 2.10.11 - e38a9aa5b1f8) and Linux, with purple-facebook 6a0a79182ebc. They are different computers in different networks. Works when disabling then enabling the facebook account. Might be related to #143.

**Comment by baronvertigovongrahamthefirstofsealand** [comment] 2015-11-04 03:11
Same things occurs to me with version 6a0a79182ebc on both Linux and Win.

**Comment by fangfufu** [comment] 2015-11-04 03:57
This is definitely related to #143, I can confirm that the problem still occur with version 6a0a79182ebc for me.

**Comment by tkedwards** [comment] 2015-11-18 07:54
Same here. It's really annoying since with laptops I'm always suspending and resuming them, e.g:
- laptop is at home on home Wifi, Pidgin Facebook plugin working normally
- close laptop lid (it automatically suspends), leave home and get on train to work
- enable hotspot on smartphone so that laptop has internet, resume laptop from suspend, it connects to hotspot automatically and has no trouble accessing the internet, but Pidgin Facebook never reconnects (even after an hour or more) unless I manually enable/disable it

Note that the problem isn't anything to do with the mobile hotspot - if I suspend and then resume the laptop while still at home on the same Wifi network the problem still happens

**Comment by jkufner** [comment] 2015-11-18 11:30
When data are not sent into TCP socket, TCP socket can survive very loooong time without detecting error. I guess the same problem will be with masquerading routers when connection is open but inactive for a few hours and record in NAT table expires. This issue is usually solved by sending keepalive packets every few minutes. These keepalive packets will also cause an error to appear when network is not available, so the connection can be reestablished.

**Comment by Adirelle** [comment] 2015-11-19 14:35
@jkufner As I understand it, the new Facebook protocol is based on HTTP(S), so there is no permanent TCP connection to manage.

**Comment by jkufner** [comment] 2015-11-19 14:42
@Adirelle Which mechanism is used for waiting for events? Most techniques have similar connection.

**Comment by dequis** [comment] 2015-11-19 14:54
@Adirelle that's just plain wrong. There's a permanent TCP connection using the MQTT protocol.

**Comment by Adirelle** [comment] 2015-11-19 21:46
@dequis My bad. I wasn't sure but since Facebook's got away from XMPP *and* provides an HTML5 client, it would have made sense to provide only one implementation of the protocol.

Anyway, purple-facebook seems to fail to reconnect after suspend and network disruption.

**Comment by tkedwards** [comment] 2015-12-21 22:40
This appears to be fixed, I have the package purple-facebook-20151220~03c5d69~86 installed in ubuntu 14.04 and the problem doesn't seem to happen

**Comment by jgeboski** [comment] 2015-12-21 22:42
@tkedwards this is actually still broken, your network is just coming online fast enough. I am actually working on a fix for this as we speak.

**Comment by tkedwards** [comment] 2015-12-21 23:52
Oh right, thanks for looking at it then!

**Comment by jgeboski** [comment] 2015-12-22 03:15
This has been resolved as of [50bb40c](https://bitbucket.org/pidgin/main/commits/50bb40c42245618dc0a2cc92901905c701ad9f58) and is in the latest release.

**Closed by jgeboski** 2015-12-22 03:15 UTC
Labels: bug

**Comment by tkedwards** [comment] 2015-12-23 22:33
Seems to work for me now in the scenario I described above (laptop on the go resuming from suspend to switch to smartphone tethered wifi) with the Ubuntu package version 20151222~10bf73d~078fbf8d1a4e~91. 

Thanks for fixing this!
