### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by curchunflo** [jgeboski/purple-facebook#22] opened 2015-07-12 15:31 UTC
Hello, since friday I can't connect with the facebook chat from Pidgin. Unexpectedly it stays kind connecting and about 1 minute after pidgin says: "server closed the connection", i asked to many friends and they have the same problem. Could you help me please?

**Comment by curchunflo** [comment] 2015-07-12 15:32
I am using Debian 7 with Pidgin from repositories (2.10.10) but my friend had tested in Ubuntu and other debian based

**Comment by freeballer** [comment] 2015-07-12 15:54
I can't tell you when it started for me, but I'm having same problem connecting to facebook. I tried updating to the latest copy and having same issue. I'm running windows 7 and pidgin 2.10.11.

**Comment by jgeboski** [comment] 2015-07-12 16:38
It sounds like you're not using the plugin, but rather still XMPP.  Please ensure you have read the [README](https://github.com/jgeboski/purple-facebook#basic-usage).  This will tell you how to not only install the plugin, but get started using it.

**Comment by freeballer** [comment] 2015-07-12 16:49
I already tried downloading both files and I installed them to the plugin folder, but it doesn't give me any new options in accounts.

**Comment by jgeboski** [comment] 2015-07-12 17:26
@freeballer read the [installation](https://github.com/jgeboski/purple-facebook#installing-on-windows) instructions closer.  Both DLL files do not go into the plugins folder.

**Comment by freeballer** [comment] 2015-07-12 17:40
well, I guess I could have have typed that with an "&" instead of a "/".. but I thought you'd notice it isn't the typical "\" used in windows path.

btw, since I posted I tried uninstalling pidgin and deleting the "C:\Program Files (x86)\Pidgin" path and re-installing. Then copying "libjson-glib-1.0.dll" to the pain pidgin directory "C:\Program Files (x86)\Pidgin\" AND copying "libfacebook.dll" to "C:\Program Files (x86)\Pidgin\plugins\"...

-- it didn't help

**Comment by jgeboski** [comment] 2015-07-12 17:47
@freeballer What version of pidgin?

**Comment by freeballer** [comment] 2015-07-12 18:41
if you re-read my first post I mention which version I was using.. but I won't be needing your help, I got it working using source.

**Comment by jgeboski** [comment] 2015-07-12 18:53
@curchunflo has your issue been fixed?

**Comment by curchunflo** [comment] 2015-07-12 23:13
thank you jgeboski no, i still have the problem. I had used pidgin with my facebook account the past 5 or 6 months but from friday suddenly i can't connect. I have not changed anything, please, if you can help me i will be very thankfull!!

**Comment by curchunflo** [comment] 2015-07-12 23:14
i was using the plugin, if not, how could I connect to facebook with pidgin?

**Comment by jgeboski** [comment] 2015-07-12 23:15
You were using XMPP, the old method.  This plugin is the method.

**Comment by jgeboski** [comment] 2015-07-12 23:15
Did you manage to install this plugin?

**Comment by curchunflo** [comment] 2015-07-13 00:06
you are right, sorrry! Now I have installed it and have a new error: Invalid HTTP response code (500), I do not know what is wrong!

**Comment by jgeboski** [comment] 2015-07-13 03:35
Closing as this issue is now a duplicate of #11.

**Closed by jgeboski** 2015-07-13 03:35 UTC
