### ISSUE TITLE
Accounts that are not in my facebook friends list

### ISSUE THREAD

**Issue by cyberalex4life** [jgeboski/purple-facebook#150] opened 2015-09-28 10:08 UTC
Issue https://github.com/jgeboski/purple-facebook/issues/68 is present again

**Comment by jgeboski** [comment] 2015-10-14 13:34
What plugin version?

**Comment by cyberalex4life** [comment] 2015-10-14 19:19
I don't know about the one that's now on master, but every version which came after the fixed version had this problem. I'll get the new one..

**Comment by cyberalex4life** [comment] 2015-10-14 19:34
So, this is the version that works well: 9e3520d6ec49, and everything else I tried with 'git clone https://github.com/jgeboski/purple-facebook' doesn't.
This is the version I just compiled and it shoes a lot of contacts that I don't have: 6a0a79182ebc

**Comment by jgeboski** [comment] 2015-12-21 00:11
This has been fixed as of [25bab54](https://bitbucket.org/pidgin/main/commits/25bab54aa2fa3fcfd2e65e544dbed2167dad8920) and will appear in the next release. This was a regression introduced by [8e23ae2](https://bitbucket.org/pidgin/main/commits/8e23ae2d2ef6225727b580bf1bcaa7a9bc18d7ea).

**Closed by jgeboski** 2015-12-21 00:11 UTC
Labels: bug

**Comment by cyberalex4life** [comment] 2015-12-24 21:56
Man, I want to thank for fixing this. but I also want to tell that I don't know for what reason, the Android Messenger works like your plugin without this fix. The Facebook Android app works like the webpage, not showing anything else. The thing is that the facebook android messenger does not offer me any option about removing those contacts. Nor have I found one in my facebook account. If someone complains about my request which you solved, please consider adding an option that can allow users to see those contacts.
If I disturbed you, please forgive me.
Happy Holidays!

**Comment by jgeboski** [comment] 2015-12-26 16:29
@cyberalex4life I do not follow you.

**Comment by cyberalex4life** [comment] 2015-12-26 16:45
Well @jgeboski, this bug I reported is also present in Android Facebook Messenger App, so I am not sure if this is a bug or a feature.

**Comment by jgeboski** [comment] 2015-12-26 16:47
For us it is a bug. This is because we work on the basis of a buddy list, unlike the mobile Messenger application. The application works on the basis of chat threads, so it make sense there.

**Comment by cyberalex4life** [comment] 2015-12-26 16:48
Ok, I am just thankful you got it fixed
