### ISSUE TITLE
Duplicate messages received

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#159] opened 2015-10-31 17:18 UTC
Sometimes I get the same message delivered 2 or 3 times. The timestamp is the same. Could you check if the last message is already present in the chat window and if so, not display the message if the timestamp (rounded to seconds) is equal?

**Comment by jgeboski** [comment] 2015-10-31 17:21
Duplicate of #155.

**Closed by jgeboski** 2015-10-31 17:21 UTC
