### ISSUE TITLE
Error message viewer

### ISSUE THREAD

**Issue by sadalavoaoj** [jgeboski/purple-facebook#181] opened 2015-12-16 23:27 UTC
Hi there,

Today i had this mistake, could somebody help please?
Cinnamon 17.3 here

Edit: I see that issue #179  so i can presume that is a facebook problem?
Edit 2: Working now. (confirmed the problem was facebook) not this amazing tool.
![captura de ecra de 2015-12-16 23 25 21](https://cloud.githubusercontent.com/assets/14188908/11856976/80007fd2-a44c-11e5-9bac-b21083238ebe.png)

**Comment by dequis** [comment] 2015-12-18 05:54
Closing as duplicate of #179 (which might need to be closed too)

**Closed by dequis** 2015-12-18 05:54 UTC
