### ISSUE TITLE
Typed wrong password, still logged in

### ISSUE THREAD

**Issue by CPColin** [jgeboski/purple-facebook#216] opened 2016-02-17 01:12 UTC
I don't have my password saved, so Pidgin asks me for my Facebook password when I start it. I accidentally typed the wrong one in and was still logged in. I can even type stuff like "nope" and it works. I'm not sure if my real password is getting cached somewhere, or what.

**Comment by Ghokun** [comment] 2016-02-18 11:49
Account information (including passwords) can be found at `~/.purple/accounts.xml`

**Comment by dequis** [comment] 2016-02-18 12:07
Duplicate of #193 

>The password is only used for the first login, it uses access tokens afterwards.

**Closed by dequis** 2016-02-18 12:07 UTC

**Comment by CPColin** [comment] 2016-02-18 15:16
In my opinion, there's two bugs, then:

1. The dialog box shows on every login, even though it's not needed after the first time.
2. A user could save his or her password in accounts.xml, even though that password isn't used.

Seems like the dialog should be suppressed, if possible, and the "Save Password" option should be disabled, again, if possible.

**Comment by dequis** [comment] 2016-02-18 15:48
I think that's all out of our control, they are pidgin UI issues.

The password is used and saving it is useful - access tokens don't last forever and the password is needed to refresh them. But we have no way to tell the UI that we need the password only sometimes.

**Comment by EionRobb** [comment] 2016-02-18 16:51
@dequis what about with the password-optional flag on the connection?
