### ISSUE TITLE
Ignore (mute) certain group chats?

### ISSUE THREAD

**Issue by random6969** [jgeboski/purple-facebook#76] opened 2015-07-28 19:13 UTC
Similar to how facebook has an option to "mute conversation" for active group chats that become too annoying, it would be nice if your Pidgin plugin could selectively ignore certain groups (stop a chat window from popping up whenever someone adds a new message).

Currently I just minimize those chat popups so they stay in the background, but it would be nice if I could close the window entirely without worrying about it randomly popping up whenever someone in the group types a message.

**Comment by jgeboski** [comment] 2015-07-29 02:37
It is not per-chat, but you can globally disable group chats from opening new windows.  Or are you implying it needs to be per-chat?

**Comment by fangfufu** [comment] 2015-07-29 06:40
I wonder if you should make it behave like IRC, @jgeboski. Perhaps if you tick the "Persistent", then you are considered to have never left the conversation, so you don't get new pop-ups.

**Comment by random6969** [comment] 2015-07-29 21:16
@jgeboski I was referring to it being per-chat.

However, I didn't realize there was also a global option for disabling all group chats. Can you explain where this option is / how to activate it?

**Comment by jgeboski** [comment] 2015-07-29 21:31
Under the account settings, go to the "Advanced" tab, and uncheck "Open new group chats with incoming messages."

**Comment by random6969** [comment] 2015-07-29 21:36
@jgeboski thanks.

**Comment by EionRobb** [comment] 2015-08-02 00:26
If you save a chat to the buddy list, then mark it as persistent, them close it, it should still receive the chat messages without popping up, the chat entry in the buddy list will just display as bold

**Comment by lmfardin** [comment] 2015-08-03 05:07
I don't have this Advanced tab. Does it mean I'm outdated? 


     Em Sábado, 1 de Agosto de 2015 21:26, Eion Robb <notifications@github.com> escreveu:
   

 If you save a chat to the buddy list, then mark it as persistent, them close it, it should still receive the chat messages without popping up, the chat entry in the buddy list will just display as bold—

**Comment by jgeboski** [comment] 2015-08-05 00:56
@lmfardin Yes.

**Comment by jgeboski** [comment] 2015-08-11 05:30
It is certainly possible to mute and unmute threads over the Messenger protocol.  The problem is that such functionality will not integrate super nicely with libpurple.  Sure, we could add two new menu options, but they will not reflect the current state of the thread.  The thread would have to be checked whenever it is loaded, and then somehow interact with the user if the thread is muted.

While it is doable, the amount of code required, and the possible confusion, outweigh the potential gains from such a feature.  If this feature is a huge demand in the future, I will reconsider the possibility of implementing it.  For now, there are other options, one of which @EionRobb mentions above.  You can also simply just disable the auto-join functionality, again as mentioned above, and then join only group chats you would like.

**Closed by jgeboski** 2015-08-11 05:30 UTC
