### ISSUE TITLE
Please use better versioning

### ISSUE THREAD

**Issue by sander85** [jgeboski/purple-facebook#145] opened 2015-09-21 15:39 UTC
The current versioning makes it almost impossible to package it for a linux distribution. It's impossible to use the version of the release as upgrade would be broken by design. Last 3 versions start with 72... -> 57... -> 6a - how is the packager supposed to make it upgradeable?

**Comment by dequis** [comment] 2015-09-21 16:56
Duplicate of #52, #119.

You could have your own version numbers, such as, 0.yyyymmdd.versionhash. That's what packagers normally do.

A 1.0 stable release will probably happen soon.

**Closed by dequis** 2015-09-21 16:56 UTC
