### ISSUE TITLE
OTR transmitting unreadable messages

### ISSUE THREAD

**Issue by cherryleafroad** [jgeboski/purple-facebook#180] opened 2015-12-16 22:23 UTC
As far as I know, this is only happening with this plugin (didn't happen with the XMPP Facebook plugin).

When I am chatting with OTR enabled, often what will happen is I will see OTR errors.

```
You transmitted an unreadable encrypted message.
```

Or vise versa, (they transmitted unreadable messages). And then OTR refreshes itself. Although I seem to always get the correct messages, but this happens constantly, and I've tried updating the plugin and also clearing out OTR settings, none of which helped to alleviate the problem.

**Comment by dequis** [comment] 2015-12-28 02:51
I tested this, it turns out it's just the message duplication bug.

![](http://dump.dequis.org/JiDAo.png)

In this screenshot, the encrypted 116 is received three times. Since the otr key changes with every message, the second and third repeats can't be decrypted and display that error (117 has the right key). When that error is shown, otr notifies the other side with a control message, so you see that "You transmitted an unreadable encrypted message.", and it considers the session to be broken so it reconnects.

Closing as duplicate of #155.

**Closed by dequis** 2015-12-28 02:51 UTC
