### ISSUE TITLE
Facebook not reconnecting after wakeup from system sleep

### ISSUE THREAD

**Issue by pschichtel** [jgeboski/purple-facebook#185] opened 2015-12-20 22:25 UTC
When sleeping my system and waking it up again, the Facebook account will not reconnect until I manually disable and re-enable it

**Comment by pschichtel** [comment] 2015-12-20 22:27
I'm on Archlinux Testing x86_64 with Kernel 4.3 (although this did already happen with 4.2)

**Comment by jgeboski** [comment] 2015-12-20 22:33
Duplicate of #138.

**Closed by jgeboski** 2015-12-20 22:33 UTC
