### ISSUE TITLE
Group chats not sorted

### ISSUE THREAD

**Issue by lmfardin** [jgeboski/purple-facebook#162] opened 2015-11-01 20:41 UTC
I use a plugin called Extended B-List Sort in order to have more criteria to sort my friends list. However, these criteria don't seem to work for Facebook group chats.

**Comment by dequis** [comment] 2015-11-01 21:24
Can you provide some examples?

What criteria did you use, what did you expect, and what did you get instead?

**Comment by lmfardin** [comment] 2015-11-02 13:02
My criteria was log size. When I sent and received some messages, I was expecting that group to move through my friends list, but it got stuck at the top. 


     Em Domingo, 1 de Novembro de 2015 19:25, dx <notifications@github.com> escreveu:
   

 Can you provide some examples?What criteria did you use, what did you expect, and what did you get instead?—

**Comment by jgeboski** [comment] 2015-12-28 22:15
Are the logs being updated, or are they disabled/empty?

**Comment by jgeboski** [comment] 2015-12-29 22:46
Is this issue only present with the log size ordering? Do these group chats have a large number of users in them?

It is worth nothing that with group chats, if there are a lot of people, the joining/parting messages are logged when entering the group chat. This has been fixed in a recent patch, [2a83ef0](https://bitbucket.org/pidgin/main/commits/2a83ef0aed865b68e4412bfd7ec27854bea694bd), and will appear in the next release. This could be causing the log size of these group chats to be rather large if there are a lot of users.

**Comment by jgeboski** [comment] 2016-01-16 15:28
Any update on this issue?

**Comment by dequis** [comment] 2016-01-30 18:08
ping

**Comment by lmfardin** [comment] 2016-02-01 04:21
Sorry for taking so long to respond.I haven't been into group chats nowadays, but I'll let you know if issue happens again. 

    Em Sábado, 30 de Janeiro de 2016 16:08, dx <notifications@github.com> escreveu:
 

 ping—

**Comment by jgeboski** [comment] 2016-02-15 16:31
Closing this for now. Reopen if the issue is still persistent.

**Closed by jgeboski** 2016-02-15 16:31 UTC
