### ISSUE TITLE
Muting a group chat in Facebook doesn't mute it in Pidgin

### ISSUE THREAD

**Issue by rrthomas** [jgeboski/purple-facebook#129] opened 2015-08-27 07:55 UTC
As far as I can tell, muting a group chat in Facebook has no effect in Pidgin.

[This plugin has gotten amazing good in an astonishingly short time; I don't remember anything like it in Pidgin's storied history. Mega props.]

**Comment by marsjaninzmarsa** [comment] 2015-08-27 09:27
+1, amazing work @jgeboski!

**Comment by dequis** [comment] 2015-08-27 14:10
Duplicate of #76, which was closed because https://github.com/jgeboski/purple-facebook/issues/76#issuecomment-129710666

That issue also mentions alternatives that are equivalent to muting group chats that can be done on the pidgin side.

**Closed by dequis** 2015-08-27 14:10 UTC

**Comment by rrthomas** [comment] 2015-08-27 15:48
Thanks for the pointer, and apologies for filing a duplicate.
